name: Nuget Pack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Pack
      run: dotnet pack

    - name: Upload NDecrypt Core package
      uses: actions/upload-artifact@v4
      with:
        name: 'NDecrypt Core Package'
        path: 'NDecrypt.Core/bin/Release/*.nupkg'

    - name: Upload NDecrypt Core to rolling
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: True
        artifacts: 'NDecrypt.Core/bin/Release/*.nupkg'
        body: 'Last built commit: ${{ github.sha }}'
        name: 'Rolling Release'
        prerelease: True
        replacesArtifacts: True
        tag: "rolling"
        updateOnlyUnreleased: True

